api:
  name: "first-country-lookup-sapi"
  host: "0.0.0.0"
  port:  "8081"
  basepath: "/api/*"
  apiId: "17552608"
  layer: "System"
  
getcountriesreq:
  host: "api.first.org"
  basepath: "/data/v1"
  countriespath: "/countries"
  connectiontimeout: "30000"
  responsetimeout: "30000"
  reconnectionretry: "3"
  reconnectionfrequency: "2000"
 